// <auto-generated />
using System;
using ContentAggregator.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ContentAggregator.Infrastructure.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260724000946_AddStructuredContentRevisions")]
    partial class AddStructuredContentRevisions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ContentAggregator.Core.Entities.Feature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstNameEng")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstNameGeo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastNameEng")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastNameGeo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Feature");
                });

            modelBuilder.Entity("ContentAggregator.Core.Entities.YTChannel", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<byte>("ActivityLevel")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastPublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TitleKeywords")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("YTChannel");
                });

            modelBuilder.Entity("ContentAggregator.Core.Entities.YoutubeContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalComments")
                        .HasColumnType("text");

                    b.Property<string>("ChannelId")
                        .IsRequired()
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("FbPosted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastProcessingError")
                        .HasColumnType("text");

                    b.Property<bool>("NeedsRefetch")
                        .HasColumnType("boolean");

                    b.Property<bool>("NotRelevant")
                        .HasColumnType("boolean");

                    b.Property<byte>("SubtitleLanguage")
                        .HasColumnType("smallint");

                    b.Property<string>("SubtitlesFiltered")
                        .HasColumnType("text");

                    b.Property<string>("SubtitlesOrigSRT")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VideoId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("VideoLength")
                        .HasColumnType("interval");

                    b.Property<DateTimeOffset>("VideoPublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VideoSummary")
                        .HasColumnType("text");

                    b.Property<string>("VideoTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("YoutubeCommentId")
                        .HasColumnType("text");

                    b.Property<bool>("YoutubeCommentPosted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("YoutubeCommentPostedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("YoutubeCommentText")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("VideoId")
                        .IsUnique();

                    b.ToTable("YoutubeContent");
                });

            modelBuilder.Entity("ContentAggregator.Core.Entities.YoutubeContentFeature", b =>
                {
                    b.Property<int>("FeatureId")
                        .HasColumnType("integer");

                    b.Property<int>("YoutubeContentId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("FeatureId", "YoutubeContentId");

                    b.HasIndex("YoutubeContentId");

                    b.ToTable("YoutubeContentFeature");
                });

            modelBuilder.Entity("ContentAggregator.Core.Entities.YoutubeContentPublication", b =>
                {
                    b.Property<int>("YoutubeContentId")
                        .HasColumnType("integer");

                    b.Property<uint>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("PublishedRevisionId")
                        .HasColumnType("integer");

                    b.Property<byte>("State")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WithdrawalReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("WithdrawnAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("YoutubeContentId");

                    b.HasIndex("YoutubeContentId", "PublishedRevisionId")
                        .IsUnique();

                    b.ToTable("YoutubeContentPublication", t =>
                        {
                            t.HasCheckConstraint("CK_YoutubeContentPublication_State", "(\"State\" = 0 AND \"PublishedRevisionId\" IS NULL AND \"PublishedAt\" IS NULL AND \"WithdrawnAt\" IS NULL AND \"WithdrawalReason\" IS NULL) OR (\"State\" = 1 AND \"PublishedRevisionId\" IS NOT NULL AND \"PublishedAt\" IS NOT NULL AND \"WithdrawnAt\" IS NULL AND \"WithdrawalReason\" IS NULL) OR (\"State\" = 2 AND \"PublishedRevisionId\" IS NOT NULL AND \"PublishedAt\" IS NOT NULL AND \"WithdrawnAt\" IS NOT NULL AND \"WithdrawalReason\" IS NOT NULL AND length(btrim(\"WithdrawalReason\")) > 0)");
                        });
                });

            modelBuilder.Entity("ContentAggregator.Core.Entities.YoutubeContentRevision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<uint>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GeneratorModel")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<byte>("Language")
                        .HasColumnType("smallint");

                    b.Property<string>("PromptVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<byte>("ReviewState")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReviewedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TranscriptChecksum")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<int>("YoutubeContentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("YoutubeContentId", "Version")
                        .IsUnique();

                    b.ToTable("YoutubeContentRevision", t =>
                        {
                            t.HasCheckConstraint("CK_YoutubeContentRevision_ApprovedReview", "\"ReviewState\" <> 3 OR (\"ReviewedAt\" IS NOT NULL AND \"ReviewedBy\" IS NOT NULL AND length(btrim(\"ReviewedBy\")) > 0)");

                            t.HasCheckConstraint("CK_YoutubeContentRevision_ReviewState", "\"ReviewState\" BETWEEN 0 AND 4");

                            t.HasCheckConstraint("CK_YoutubeContentRevision_TranscriptChecksum", "length(btrim(\"TranscriptChecksum\")) > 0");

                            t.HasCheckConstraint("CK_YoutubeContentRevision_Version", "\"Version\" > 0");
                        });
                });

            modelBuilder.Entity("ContentAggregator.Core.Entities.YoutubeContentSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Confidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EndSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("Heading")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer");

                    b.Property<byte>("Source")
                        .HasColumnType("smallint");

                    b.Property<int>("StartSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<int>("YoutubeContentRevisionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("YoutubeContentRevisionId", "Ordinal")
                        .IsUnique();

                    b.ToTable("YoutubeContentSection", t =>
                        {
                            t.HasCheckConstraint("CK_YoutubeContentSection_Confidence", "\"Confidence\" IS NULL OR \"Confidence\" BETWEEN 0 AND 1");

                            t.HasCheckConstraint("CK_YoutubeContentSection_EndSeconds", "\"EndSeconds\" IS NULL OR \"EndSeconds\" > \"StartSeconds\"");

                            t.HasCheckConstraint("CK_YoutubeContentSection_Heading", "length(btrim(\"Heading\")) > 0");

                            t.HasCheckConstraint("CK_YoutubeContentSection_Ordinal", "\"Ordinal\" >= 0");

                            t.HasCheckConstraint("CK_YoutubeContentSection_Source", "\"Source\" BETWEEN 0 AND 1");

                            t.HasCheckConstraint("CK_YoutubeContentSection_StartSeconds", "\"StartSeconds\" >= 0");
                        });
                });

            modelBuilder.Entity("ContentAggregator.Core.Entities.YoutubeContent", b =>
                {
                    b.HasOne("ContentAggregator.Core.Entities.YTChannel", "YTChannel")
                        .WithMany("YoutubeContents")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("YTChannel");
                });

            modelBuilder.Entity("ContentAggregator.Core.Entities.YoutubeContentFeature", b =>
                {
                    b.HasOne("ContentAggregator.Core.Entities.Feature", null)
                        .WithMany("YoutubeContentFeatures")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContentAggregator.Core.Entities.YoutubeContent", null)
                        .WithMany("YoutubeContentFeatures")
                        .HasForeignKey("YoutubeContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ContentAggregator.Core.Entities.YoutubeContentPublication", b =>
                {
                    b.HasOne("ContentAggregator.Core.Entities.YoutubeContent", "YoutubeContent")
                        .WithOne("Publication")
                        .HasForeignKey("ContentAggregator.Core.Entities.YoutubeContentPublication", "YoutubeContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContentAggregator.Core.Entities.YoutubeContentRevision", "PublishedRevision")
                        .WithOne("Publication")
                        .HasForeignKey("ContentAggregator.Core.Entities.YoutubeContentPublication", "YoutubeContentId", "PublishedRevisionId")
                        .HasPrincipalKey("ContentAggregator.Core.Entities.YoutubeContentRevision", "YoutubeContentId", "Id")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("PublishedRevision");

                    b.Navigation("YoutubeContent");
                });

            modelBuilder.Entity("ContentAggregator.Core.Entities.YoutubeContentRevision", b =>
                {
                    b.HasOne("ContentAggregator.Core.Entities.YoutubeContent", "YoutubeContent")
                        .WithMany("Revisions")
                        .HasForeignKey("YoutubeContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("YoutubeContent");
                });

            modelBuilder.Entity("ContentAggregator.Core.Entities.YoutubeContentSection", b =>
                {
                    b.HasOne("ContentAggregator.Core.Entities.YoutubeContentRevision", "YoutubeContentRevision")
                        .WithMany("Sections")
                        .HasForeignKey("YoutubeContentRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("YoutubeContentRevision");
                });

            modelBuilder.Entity("ContentAggregator.Core.Entities.Feature", b =>
                {
                    b.Navigation("YoutubeContentFeatures");
                });

            modelBuilder.Entity("ContentAggregator.Core.Entities.YTChannel", b =>
                {
                    b.Navigation("YoutubeContents");
                });

            modelBuilder.Entity("ContentAggregator.Core.Entities.YoutubeContent", b =>
                {
                    b.Navigation("Publication");

                    b.Navigation("Revisions");

                    b.Navigation("YoutubeContentFeatures");
                });

            modelBuilder.Entity("ContentAggregator.Core.Entities.YoutubeContentRevision", b =>
                {
                    b.Navigation("Publication");

                    b.Navigation("Sections");
                });
#pragma warning restore 612, 618
        }
    }
}
