using ContentAggregator.Core.Entities;

namespace ContentAggregator.Core.Models
{
    public class Constants
    {
        private const string AISummaryDisclaimerGeo = "შეჯამება შედგენილია AI-ს მიერ და შეიძლება შეიცავდეს შეცდომებს.";
        private const string AISummaryDisclaimerEng = "This summary was generated by AI and may contain errors.";
        private const string AISummaryDisclaimerRus = "Сводка создана ИИ и может содержать ошибки.";

        public static string GetAiSummaryDisclaimer(SubtitleLanguage language)
        {
            return language switch
            {
                SubtitleLanguage.Georgian => AISummaryDisclaimerGeo,
                SubtitleLanguage.Russian => AISummaryDisclaimerRus,
                _ => AISummaryDisclaimerEng
            };
        }
    }
}
