using ContentAggregator.Core.Entities;

namespace ContentAggregator.Application.Support
{
    public static class AiSummaryDisclaimer
    {
        private const string Georgian = "შეჯამება შედგენილია AI-ს მიერ და შეიძლება შეიცავდეს შეცდომებს.";
        private const string English = "This summary was generated by AI and may contain errors.";
        private const string Russian = "Сводка создана ИИ и может содержать ошибки.";

        public static string GetText(SubtitleLanguage language)
        {
            return language switch
            {
                SubtitleLanguage.Georgian => Georgian,
                SubtitleLanguage.Russian => Russian,
                _ => English
            };
        }
    }
}
